FROM alpine:3.22 AS base

ARG APP_VERSION

RUN set -ex; \
    apk add --no-cache \
        bzip2 \
        curl \
        gnupg \
        rsync \
        util-linux \
        shadow;

RUN set -ex; \
    mkdir -p /var/www/nextcloud; \
    groupmod -g 101 -o www-data; \
    adduser -h /var/www/nextcloud -H -s /sbin/nologin -S -u 101 -G www-data www-data;

ENV NEXTCLOUD_VERSION=${APP_VERSION}

RUN set -ex; \
    curl -fsSL -o nextcloud.tar.bz2 \
        "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2"; \
    curl -fsSL -o nextcloud.tar.bz2.asc \
        "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc"; \
    export GNUPGHOME="$(mktemp -d)"; \
    # gpg key from https://nextcloud.com/nextcloud.asc
    gpg --batch --keyserver keyserver.ubuntu.com  --recv-keys 28806A878AE423A28372792ED75899B9A724937A; \
    gpg --batch --verify nextcloud.tar.bz2.asc nextcloud.tar.bz2; \
    tar -xjf nextcloud.tar.bz2 -C /var/www/; \
    gpgconf --kill all; \
    rm nextcloud.tar.bz2.asc nextcloud.tar.bz2; \
    rm -rf "$GNUPGHOME"; \
    mkdir -p /var/www/nextcloud/data; \
    mkdir -p /var/www/nextcloud/custom_apps; \
    chmod +x /var/www/nextcloud/occ; \
    chown -R www-data:www-data /var/www; \
    chmod -R g=u /var/www;

WORKDIR /var/www/nextcloud

VOLUME /var/www/nextcloud/data
VOLUME /var/www/nextcloud/custom_apps
VOLUME /var/www/nextcloud/config
VOLUME /var/www/nextcloud/themes


# The nginx target of this file
FROM base AS nginx

RUN set -ex; \
    apk add --no-cache \
        nginx \
        nginx-mod-http-brotli;

COPY nginx.conf /etc/nginx/nginx.conf

USER nginx:www-data

CMD ["nginx", "-c", "/etc/nginx/nginx.conf"]


# The php-fpm target of this file
FROM base AS php-fpm

RUN set -ex; \
    apk add --no-cache \
        ffmpeg \
        imagemagick \
        imagemagick-heic \
        imagemagick-jpeg \
        imagemagick-svg \
        imagemagick-tiff \
        imagemagick-webp \
        php83 \
        php83-fpm \
        php83-bcmath \
        php83-bz2 \
        php83-ctype \
        php83-curl \
        php83-dom \
        php83-exif \
        php83-fileinfo \
        php83-gd \
        php83-gmp \
        php83-iconv \
        php83-intl \
        php83-ldap \
        php83-mbstring \
        php83-opcache \
        php83-openssl \
        php83-pcntl \
        php83-pdo_pgsql \
        php83-posix \
        php83-session \
        php83-simplexml \
        php83-sodium \
        php83-sysvsem \
        php83-xml \
        php83-xmlreader \
        php83-xmlwriter \
        php83-zip \
        php83-pecl-apcu \
        php83-pecl-memcached \
        php83-pecl-imagick \
        php83-pecl-redis; \
    ln -sf /usr/bin/php83 /usr/bin/php; \
    ln -sf /usr/sbin/php-fpm83 /usr/sbin/php-fpm;

# set recommended PHP.ini settings
# see https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html#enable-php-opcache
ENV PHP_MEMORY_LIMIT=512M
ENV PHP_UPLOAD_LIMIT=1024M
COPY php.conf.d/ /etc/php83/conf.d/
COPY php-fpm.d/ /etc/php83/php-fpm.d/

# Setup cronjob
RUN set -ex; \
    rm /var/spool/cron/crontabs/root; \
    echo '*/5 * * * * php -f /var/www/nextcloud/cron.php' > /var/spool/cron/crontabs/www-data;

COPY entrypoint.sh upgrade.sh /
COPY config/* /usr/share/nextcloud/config/

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm", "-F"]
