---
name: "Package phpldapadmin"
on:
  push:
    branches:
      - main
      - test
      - dev
    paths:
      - 'phpldapadmin/**'
  workflow_dispatch: {}

jobs:
  package-phpldapadmin:
    uses: "./.github/workflows/package.yml"
    with:
      name: phpldapadmin
      path: phpldapadmin
